resources:
  - ../base
components:
  - ../in-place-scaling
  - ../pod-updater
  - ../status-labels
  - ../status-events
  - ../migration-manager
  - ../capacity-request
  - ../reuseport-activator
images:
  - name: manager
    newName: docker.io/laravelphp/zeropod-manager
    newTag: dev
  - name: installer
    newName: docker.io/laravelphp/zeropod-installer
    newTag: dev
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: -debug=true
    target:
      kind: DaemonSet
